title: "Wireless Earbuds For Small Ears"
description: "Insights and guides about wireless earbuds for small ears"
theme: jekyll-theme-minimal
url: "https://calcifergtp-glitch.github.io"
baseurl: "/wireless-earbuds-for-small-ears"
plugins:
  - jekyll-sitemap
